language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
# Command to install all dependencies
install:
  - pip install -r requirements.txt
# Command to run tests
script:
  #- python -m unittest discover -t ..
  - coverage run --source=spacetracktool -m unittest discover -t ..
after_success:
  - coveralls
#branches:
#  only:
#  - master
